config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :users, except: %i[index edit update] do
    resources :games, except: %i[external edit update]
  end
  resources :genres, except: %i[edit update]
  resources :games, only: 'external'
  resources :sessions, only: %i[create new destroy]
  root 'sessions#new'
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  post '/games', to: 'games#create'
  post '/genres', to: 'genres#create'
  get '/external', to: 'games#external'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/genre.rb
class Genre < ApplicationRecord
  belongs_to :user
  has_many :genre_games, dependent: :destroy
  has_many :games, through: :genre_games
  validates :name, presence: true
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  before_action :set_genre, only: %i[show edit update destroy]

  # GET /genres or /genres.json
  def index
    @genres = Genre.order('LOWER(name)')
  end

  # GET /genres/1 or /genres/1.json
  def show
    @genre = Genre.find(params[:id])
  end

  # GET /genres/new
  def new
    @icons = %w[adventure city_sim fighting horror life_sim musical platformer puzzle racing
                rougelike rpg shooter space_sim sport stealth strategy]
    @genre = Genre.new
  end

  # GET /genres/1/edit
  def edit; end

  # POST /genres or /genres.json
  def create
    @genre = current_user.genres.build(genre_params)
    @icon = params[:icon]
    @genre.icon = if @icon.nil?
                    'none'
                  else
                    @icon
                  end
    respond_to do |format|
      if @genre.save
        format.html { redirect_to genres_path, notice: 'Genre was successfully created.' }
        format.json { render :show, status: :created, location: @genre }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @genre.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /genres/1 or /genres/1.json
  def update
    respond_to do |format|
      if @genre.update(genre_params)
        format.html { redirect_to genres_path, notice: 'Genre was successfully updated.' }
        format.json { render :show, status: :ok, location: @genre }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @genre.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /genres/1 or /genres/1.json
  def destroy
    @genre = Genre.find(params[:id])
    @genre.destroy!
    redirect_to genres_path
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_genre
    @genre = Genre.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def genre_params
    params.require(:genre).permit(:name, :icon)
  end
end

app/helpers/genres_helper.rb
module GenresHelper
  def lister(genres)
    @line = ActiveSupport::SafeBuffer.new
    genres.each do |x|
      @line << content_tag(:p,
                           content_tag(:strong, link_to(x.name.to_s, genre_path(x.id), class: 'p-1 main-text'),
                                       class: 'main-text h4 row justify-content-center'))
    end
    @line
  end

  def genre_games_list(games)
    @row = ActiveSupport::SafeBuffer.new
    games.each do |x|
      @user = User.find(x.user_id)
      @row << content_tag(:tr) do
        @table = content_tag(:td, x.name, class: 'main-text text-center align-middle')
        @table << content_tag(:td, x.amount, class: 'main-text text-center align-middle')
        @table << content_tag(:td, @user.name, class: %w[main-text text-center align-middle])
      end
    end.join.html_safe
    @row
  end

  def genre_icons_lister(icons)
    @line = ActiveSupport::SafeBuffer.new
    icons.each do |x|
      @line << image_tag("#{x}.png", alt: x.to_s, size: '50x50', class: 'm-1')
      @line << radio_button_tag(:icon, x.to_s)
    end
    @line
  end

  def genre_destroy_button(genre)
    return unless genre.user_id == current_user.id

    content_tag(:p,
                content_tag(:strong,
                            link_to('Destroy', genre_path(genre), method: :delete, data: { confirm: 'Are you sure?' }, class: 'main-text'), class: 'main-text h4 row justify-content-center')) # rubocop:disable Layout/LineLength
  end
end

app/views/genres/_form.html.erb
<div class="row">
  <div class="col mx-2 col-md-6 mx-md-auto px-0">
    <%= form_with(model: genre) do |form| %>

      <h1 class = "h1 text-center">Name</h1>

      <div class="field d-flex justify-content-center">
        <%= form.text_field :name, class: "form-control col-8" %>
      </div>

      <h1 class = "h1 text-center mt-2">Icon</h1>

      <div class="field d-flex justify-content-center mb-5 row col-12 mx-n1">
        <%= genre_icons_lister(@icons)  %>
      </div>

      <div class="actions main-text h4 row justify-content-center mt-3">
        <%= form.submit "Create Genre", class: "mt-2 btn login-btn" %>
      </div>
    <% end %>
  </div>
</div>

app/views/genres/edit.html.erb
<h1>Editing Genre</h1>

<%= render 'form', genre: @genre %>

<%= link_to 'Show', @genre %> |
<%= link_to 'Back', genres_path %>

app/views/genres/index.html.erb
<p id="notice" class = "row d-flex justify-content-center h4"><%= notice %></p>

<h1 class = "h1 text-center mb-5">Genres</h1>


  <%= lister(@genres) %>


<p class = "mt-4 col-6 mx-auto border-top">
  <strong class="main-text h4 row justify-content-center mt-4"><%= link_to 'New Genre', new_genre_path, class: "p-1 main-text"%></strong>
</p>

app/views/genres/new.html.erb
<h1 class = "h1 text-center my-4">New Genre</h1>

<%= render 'form', genre: @genre %>

<p>
  <strong class="main-text h4 row justify-content-center"><%= link_to 'Back', genres_path, class: "p-1 main-text"%></strong>
</p>

app/views/genres/show.html.erb
<p id="notice" class = "row d-flex justify-content-center h4"><%= notice %></p>

<p>
  <h1 class = "h1 text-center mb-2">Title:</h1>
  <p class = "h3 text-center mb-4"><%= @genre.name %></p>
</p>

<p>
  <h1 class = "h1 text-center mb-2">Icon:</h1>
  <p class = "h3 text-center mb-4"><%= image_tag("#{@genre.icon}.png") %></p>
</p>

<p>
  <h1 class = "h1 text-center mb-2">Created At:</h1>
  <p class = "h3 text-center mb-4"><%= @genre.created_at %></p>
</p>

<p>
  <h1 class = "h1 text-center">Games</h1>
</p>

<table class = "table table-hover">
  <tr>
    <th scope="col" class = "text-center h4">Title</th>
    <th scope="col" class = "text-center h4">Cost</th>
    <th scope="col" class = "text-center h4">Author</th>
  </tr>
  <tbody>
    <%= genre_games_list(@genre.games.all)%>
  </tbody>
</table>



<%= genre_destroy_button(@genre) %>
<p>
  <strong class="main-text h4 row justify-content-center"><%= link_to 'Back', genres_path, class: "main-text" %></strong>
</p>