config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :users, except: %i[index edit update] do
    resources :games, except: %i[external edit update]
  end
  resources :genres, except: %i[edit update]
  resources :games, only: 'external'
  resources :sessions, only: %i[create new destroy]
  root 'sessions#new'
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  post '/games', to: 'games#create'
  post '/genres', to: 'genres#create'
  get '/external', to: 'games#external'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  has_many :games, dependent: :destroy
  has_many :genres, dependent: :destroy
  validates :name, presence: true, uniqueness: { case_sensitive: false }
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]
  skip_before_action :login_required, only: %i[new create]
  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show; end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit; end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)
    respond_to do |format|
      if @user.save
        log_in(@user)
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def user_params
    params.require(:user).permit(:name)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<div class="row">
  <div class="col mx-2 col-md-6 mx-md-auto">
    <%= form_with(model: user) do |f| %>
      <%= f.label :name, class: 'form-text main-text' %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.submit "Create User", class: " my-2 btn signup-link" %>
    <% end %>
  </div>
</div>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice" class = "row d-flex justify-content-center h4"><%= notice %></p>

<p class="row d-flex justify-content-center">
  <strong class="main-text h2 mb-5 font-weight-bold">Oh, you shouldn't be here.</strong>
</p>


<p>
  <strong class="main-text h4 row justify-content-center"><%= link_to 'Go Back', user_path(current_user), class: "p-1 main-text"%></strong>
</p>

app/views/users/new.html.erb
<h1 class = "h1 text-center title">New User</h1>

<%= render 'form', user: @user %>

<p>
  <strong class="main-text h4 row justify-content-center"><%= link_to 'Back', root_path, class: "p-1 main-text"%></strong>
</p>

app/views/users/show.html.erb
<p id="notice" class = "row d-flex justify-content-center h4"><%= notice %></p>

<p class="row d-flex justify-content-center">
  <strong class="main-text h2 mb-5 font-weight-bold">Hello, <%= @user.name %>! </strong>
</p>

<p>
  <strong class="main-text h4 row justify-content-center"><%= link_to 'Games', user_games_path(current_user), class: "p-1 main-text" %></strong>
</p>

<p>
  <strong class="main-text h4 row justify-content-center"><%= link_to 'Games Without Genres', '/external', class: "p-1 main-text" %></strong>
</p>

<p>
  <strong class="main-text h4 row justify-content-center"><%= link_to 'Genres', genres_path, class: "p-1 main-text"%></strong>
</p>