config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :users, except: %i[index edit update] do
    resources :games, except: %i[external edit update]
  end
  resources :genres, except: %i[edit update]
  resources :games, only: 'external'
  resources :sessions, only: %i[create new destroy]
  root 'sessions#new'
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  post '/games', to: 'games#create'
  post '/genres', to: 'genres#create'
  get '/external', to: 'games#external'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/game.rb
class Game < ApplicationRecord
  belongs_to :user
  has_many :genre_games, dependent: :destroy
  has_many :genres, through: :genre_games
  validates :name, presence: true
  scope :external, -> { includes(:genres).where(genres: { id: nil }) }
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: %i[show edit update destroy]

  # GET /games or /games.json
  def index
    @games = current_user.games.order(created_at: :DESC).includes(:genres)
    @total = 0
    @games.each { |x| @total += x.amount }
  end

  # GET /games/1 or /games/1.json
  def show
    @game = Game.find(params[:id])
    @genres = @game.genres.all
  end

  # GET /games/new
  def new
    @game = current_user.games.new
  end

  # GET /games/1/edit
  def edit; end

  def external
    @genreless = Game.external.all
  end

  # POST /games or /games.json
  def create
    @genre = current_user.genres.all
    @game = current_user.games.build(game_params)
    @genres = params[:genre]
    @game.amount = 0 if @game.amount.nil?
    respond_to do |format|
      if @game.save
        @genres&.each { |x| @game.genres << Genre.find(x) }
        format.html { redirect_to user_games_path(current_user), notice: 'Game was successfully created.' }
        format.json { render :show, status: :created, location: user_game_path(current_user, @game) }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /games/1 or /games/1.json
  def update
    @game = current_user.games.find_by(params[:id])
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to user_games_path, notice: 'Game was successfully updated.' }
        format.json { render :show, status: :ok, location: @game }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1 or /games/1.json
  def destroy
    @game = current_user.games.find(params[:id])
    @game.destroy!
    redirect_to user_games_path(current_user)
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_game
    @game = Game.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def game_params
    params.require(:game).permit(:name, :amount)
  end
end

app/helpers/games_helper.rb
module GamesHelper
  def game_display(games, external)
    @row = ActiveSupport::SafeBuffer.new
    games.each do |x|
      @row << content_tag(:tr) do
        @table = content_tag(:td, x.name, class: 'main-text text-center align-middle')
        @table << content_tag(:td, x.created_at, class: 'main-text text-center creation-date align-middle')
        @table << content_tag(:td, x.amount, class: 'main-text text-center align-middle')
        unless external
          @table << content_tag(:td, class: 'align-middle text-center main-text') do
            image_tag("#{x.genres.first.icon}.png", size: '50x50', class: '') unless x.genres.empty?
          end
        end
        @table << content_tag(:td, link_to('Show', user_game_path(current_user, x.id), class: 'main-text'),
                              class: 'main-text text-center align-middle')
      end
    end.join.html_safe
    @row
  end

  def game_genre_list(genres)
    @row = ActiveSupport::SafeBuffer.new
    genres.each do |x|
      @row << content_tag(:tr) do
        @table = content_tag(:td, x.name, class: 'text-center align-middle main-text')
        @table << content_tag(:td, image_tag("#{x.icon}.png", size: '60x60'),
                              class: 'main-text text-center')
      end
    end
    @row
  end

  def game_destroy_button(game)
    return unless game.user_id == current_user.id

    content_tag(:p,
                content_tag(:strong,
                            link_to('Destroy', user_game_path(current_user, game), method: :delete, data: { confirm: 'Are you sure?' }, class: 'main-text'), class: 'main-text h4 row justify-content-center')) # rubocop:disable Layout/LineLength
  end
end

app/views/games/_form.html.erb
<div class="row">
  <div class="col mx-2 col-md-6 mx-md-auto">
    <%= form_with(model: game) do |form| %>
      <h1 class = "h1 text-center">Name</h1>

      <div class="field d-flex justify-content-center">
        <%= form.text_field :name, class: "form-control" %>
      </div>

      <h1 class = "h1 text-center mt-2">Amount</h1>

      <div class="field d-flex justify-content-center">
        <%= form.number_field :amount, step: 0.01,  class: "form-control" %>
      </div>
      <h1 class = "h1 text-center">Genres</h1>
      <p class = "main-text text-center"> (Hold CTRL to select multiple options)</p>
      <div class = "d-flex justify-content-center mb-3">
        <%= select_tag :genre, options_from_collection_for_select(Genre.all, :id, :name), {multiple: true, class:"form-control"} %>
      </div>
      <div class="actions main-text h4 row justify-content-center">
        <%= form.submit "Create Game", class: "mt-2 btn login-btn" %>
      </div>
    <% end %>
  </div>
</div>

app/views/games/edit.html.erb
<h1>Editing Game</h1>

<%= render 'form', game: @game %>

<%= link_to 'Back', user_games_path(current_user) %>

app/views/games/external.html.erb
<p id="notice" class = "row d-flex justify-content-center h4"><%= notice %></p>

<h1 class = "h1 text-center my-5">Games Without Genres</h1>

<table class = "table table-hover">
  <thead>
    <tr>
      <th class = "main-text text-center">Title</th>
      <th class = "main-text text-center">Date</th>
      <th class = "main-text px-3 text-center">Cost</th>
      <th colspan="6"></th>
    </tr>
  </thead>

  <tbody>
    <%= game_display(@genreless, true) %>
  </tbody>
</table>

<br>

<p>
  <strong class="main-text h4 row justify-content-center"><%= link_to 'New Game', new_user_game_path(current_user), class: "p-1 main-text"%></strong>
</p>

app/views/games/index.html.erb
<p id="notice" class = "row d-flex justify-content-center h4"><%= notice %></p>

<h1 class = "h1 text-center my-5">Games</h1>

<h1 class = "h1 text-center mt-5 border-bottom">Total Cost:</h1>

<h1 class = "h3 text-center mb-5"><%= @total %></h1>

<table class = "table table-hover">
  <thead>
    <tr>
      <th class = "main-text text-center">Title</th>
      <th class = "main-text text-center">Date</th>
      <th class = "main-text px-3 text-center">Cost</th>
      <th class = "main-text text-center">Icon</th>
      <th colspan="6"></th>
    </tr>
  </thead>

  <tbody>
     <%= game_display(@games, false) %>
  </tbody>
</table>

<br>

<p>
  <strong class="main-text h4 row justify-content-center"><%= link_to 'New Game', new_user_game_path(current_user), class: "p-1 main-text"%></strong>
</p>

app/views/games/new.html.erb
<h1 class = "h1 text-center my-5">New Game</h1>

<%= render 'form', game: @game %>
<p>
  <strong class="main-text h4 row justify-content-center"><%= link_to 'Back', user_games_path(current_user), class: "p-1 main-text"%></strong>
</p>

app/views/games/show.html.erb
<p id="notice" class = "row d-flex justify-content-center h4"><%= notice %></p>

<p>
  <h1 class = "h1 text-center">Title:</h1>
  <p class = "h3 text-center"><%= @game.name %></p>
</p>

<p>
  <h1 class = "h1 text-center">Cost:</h1>
  <p class = "h3 text-center"><%= @game.amount %></p>
</p>

<p>
  <h1 class = "h1 text-center">Genres</h1>
</p>
<table class = "table table-hover">
  <tr>
    <th scope="col" class = "text-center h4">Name</th>
    <th scope="col" class = "text-center h4">Icon</th>
  </tr>
  <tbody>
    <%= game_genre_list(@game.genres.all) %>
  </tbody>
</table>

<br>

<%= game_destroy_button(@game) %>

<p>
  <strong class="main-text h4 row justify-content-center"><%= link_to 'Back', user_games_path(current_user), class: "main-text" %></strong>
</p>